function figureHandle = pa_conceptual_summary()
% PA_CONCEPTUAL_SUMMARY Create a biology-first summary of the PA model.
%
%   FIGUREHANDLE = PA_CONCEPTUAL_SUMMARY() draws a three-stage conceptual
%   diagram of the proposed disease loop, its interruption by baxdrostat,
%   and the two possible post-withdrawal outcomes. The function writes
%   pa_conceptual_summary.png and pa_conceptual_summary.pdf beside this file.

    outputFolder = fileparts(mfilename("fullpath"));
    figureHandle = figure( ...
        Color="white", ...
        Units="inches", ...
        Position=[1.0, 1.0, 13.0, 8.3]);

    palette = struct();
    palette.panel = [0.965, 0.970, 0.978];
    palette.border = [0.30, 0.34, 0.40];
    palette.text = [0.12, 0.14, 0.18];
    palette.aldosterone = [1.00, 0.89, 0.70];
    palette.salt = [0.79, 0.90, 0.98];
    palette.capacity = [0.88, 0.82, 0.95];
    palette.drug = [0.76, 0.93, 0.88];
    palette.decision = [0.93, 0.91, 0.82];
    palette.remission = [0.80, 0.94, 0.82];
    palette.relapse = [0.98, 0.82, 0.82];
    palette.arrow = [0.20, 0.23, 0.28];
    palette.green = [0.12, 0.48, 0.24];
    palette.red = [0.72, 0.18, 0.18];

    % Panel backgrounds are created first so all other objects remain visible.
    panelBox(figureHandle, [0.035, 0.655, 0.930, 0.300], palette);
    panelBox(figureHandle, [0.035, 0.405, 0.930, 0.205], palette);
    panelBox(figureHandle, [0.035, 0.045, 0.930, 0.315], palette);

    panelTitle(figureHandle, [0.055, 0.902, 0.890, 0.035], ...
        "A   Untreated PA: a self-sustaining disease loop", palette);
    panelTitle(figureHandle, [0.055, 0.558, 0.890, 0.035], ...
        "B   A finite baxdrostat course interrupts the loop", palette);
    panelTitle(figureHandle, [0.055, 0.308, 0.890, 0.035], ...
        "C   After withdrawal: suppression-resistant burden determines the outcome", ...
        palette);

    % Panel A: the proposed positive-feedback loop.
    processBox(figureHandle, [0.075, 0.765, 0.220, 0.095], ...
        "High aldosterone", palette.aldosterone, palette);
    processBox(figureHandle, [0.390, 0.765, 0.220, 0.095], ...
        "High effective volume /" + newline + "MR activation state", palette.salt, palette);
    processBox(figureHandle, [0.705, 0.765, 0.220, 0.095], ...
        "Plastic autonomous" + newline + "capacity is maintained", ...
        palette.capacity, palette);

    straightArrow(figureHandle, [0.296, 0.387], [0.813, 0.813], palette.arrow);
    arrowLabel(figureHandle, [0.297, 0.828, 0.088, 0.035], ...
        "promotes", palette.text);
    straightArrow(figureHandle, [0.611, 0.702], [0.813, 0.813], palette.arrow);
    arrowLabel(figureHandle, [0.610, 0.828, 0.092, 0.035], ...
        "sustains", palette.text);

    annotation(figureHandle, "line", [0.815, 0.815], [0.765, 0.704], ...
        Color=palette.arrow, LineWidth=1.7);
    annotation(figureHandle, "line", [0.815, 0.185], [0.704, 0.704], ...
        Color=palette.arrow, LineWidth=1.7);
    straightArrow(figureHandle, [0.185, 0.185], [0.704, 0.762], palette.arrow);
    arrowLabel(figureHandle, [0.405, 0.662, 0.190, 0.032], ...
        "supports autonomous output", palette.text);

    % Panel B: the treatment course removes support from plastic capacity.
    processBox(figureHandle, [0.075, 0.445, 0.220, 0.085], ...
        "Baxdrostat suppresses" + newline + "aldosterone production", ...
        palette.drug, palette);
    processBox(figureHandle, [0.390, 0.445, 0.220, 0.085], ...
        "Sodium-volume /" + newline + "MR drive falls", palette.salt, palette);
    processBox(figureHandle, [0.705, 0.445, 0.220, 0.085], ...
        "Plastic capacity" + newline + "loses support", ...
        palette.capacity, palette);

    straightArrow(figureHandle, [0.296, 0.387], [0.487, 0.487], palette.arrow);
    straightArrow(figureHandle, [0.611, 0.702], [0.487, 0.487], palette.arrow);

    % Panel C: branch according to the suppression-resistant burden.
    processBox(figureHandle, [0.350, 0.225, 0.300, 0.065], ...
        "How much suppression-resistant capacity remains?", ...
        palette.decision, palette);

    straightArrow(figureHandle, [0.440, 0.260], [0.224, 0.176], palette.green);
    straightArrow(figureHandle, [0.560, 0.740], [0.224, 0.176], palette.red);

    outcomeBox(figureHandle, [0.070, 0.060, 0.380, 0.110], ...
        "BELOW THRESHOLD" + newline + ...
        "Plastic capacity collapses to a low state" + newline + ...
        "Low aldosterone persists after withdrawal" + newline + ...
        "DURABLE REMISSION", palette.remission, palette.green, palette);
    outcomeBox(figureHandle, [0.550, 0.060, 0.380, 0.110], ...
        "ABOVE THRESHOLD" + newline + ...
        "Residual output re-establishes the salt bridge" + newline + ...
        "High aldosterone returns after withdrawal" + newline + ...
        "RELAPSE", palette.relapse, palette.red, palette);

    pngPath = fullfile(outputFolder, "pa_conceptual_summary.png");
    pdfPath = fullfile(outputFolder, "pa_conceptual_summary.pdf");
    exportgraphics(figureHandle, pngPath, Resolution=300);
    exportgraphics(figureHandle, pdfPath, ContentType="vector");

    fprintf("Conceptual summary written to:\n  %s\n  %s\n", pngPath, pdfPath);
end

function panelBox(figureHandle, position, palette)
    annotation(figureHandle, "rectangle", position, ...
        Color=[0.78, 0.80, 0.84], ...
        FaceColor=palette.panel, ...
        LineWidth=1.0);
end

function panelTitle(figureHandle, position, label, palette)
    annotation(figureHandle, "textbox", position, ...
        String=label, ...
        Interpreter="none", ...
        FontName="Arial", ...
        FontSize=14, ...
        FontWeight="bold", ...
        Color=palette.text, ...
        EdgeColor="none", ...
        HorizontalAlignment="left", ...
        VerticalAlignment="middle", ...
        Margin=0);
end

function processBox(figureHandle, position, label, fillColor, palette)
    annotation(figureHandle, "textbox", position, ...
        String=label, ...
        Interpreter="none", ...
        FontName="Arial", ...
        FontSize=12, ...
        FontWeight="bold", ...
        Color=palette.text, ...
        EdgeColor=palette.border, ...
        BackgroundColor=fillColor, ...
        LineWidth=1.4, ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle", ...
        Margin=5);
end

function outcomeBox(figureHandle, position, label, fillColor, edgeColor, palette)
    annotation(figureHandle, "textbox", position, ...
        String=label, ...
        Interpreter="none", ...
        FontName="Arial", ...
        FontSize=11.5, ...
        FontWeight="bold", ...
        Color=palette.text, ...
        EdgeColor=edgeColor, ...
        BackgroundColor=fillColor, ...
        LineWidth=1.8, ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle", ...
        Margin=5);
end

function straightArrow(figureHandle, x, y, color)
    annotation(figureHandle, "arrow", x, y, ...
        Color=color, ...
        LineWidth=1.8, ...
        HeadLength=9, ...
        HeadWidth=9);
end

function arrowLabel(figureHandle, position, label, color)
    annotation(figureHandle, "textbox", position, ...
        String=label, ...
        Interpreter="none", ...
        FontName="Arial", ...
        FontSize=10.5, ...
        FontWeight="bold", ...
        Color=color, ...
        EdgeColor="none", ...
        HorizontalAlignment="center", ...
        VerticalAlignment="middle", ...
        Margin=0);
end
