function results = pa_global_robustness()
%PA_GLOBAL_ROBUSTNESS Simultaneous-parameter robustness of PA bistability.
%
%   RESULTS = PA_GLOBAL_ROBUSTNESS() uses a reproducible Latin-hypercube
%   design to vary all 16 parameters that determine equilibrium locations
%   simultaneously from 80% to 120% of their nominal values. For every
%   sampled parameter set, the analysis:
%
%     * counts equilibria at z_fixed = 0.05 and sodium sigma = 0;
%     * verifies their stability with the full four-state Jacobian;
%     * finds the physical bistable interval in z_fixed;
%     * locates the healthy-saddle fold at sigma = 0 and sigma = 0.2; and
%     * tests whether sodium lowers the remission-capable threshold.
%
%   epsilon and tau_s are intentionally not sampled because they alter
%   timescales but not equilibrium locations. z_fixed and sodium are treated
%   as prediction variables rather than uncertain model parameters.
%
%   Files written beside this function:
%       pa_global_robustness.png
%       pa_global_robustness.pdf
%       pa_global_robustness_summary.csv
%       pa_global_robustness_associations.csv
%       pa_global_robustness_samples.csv
%       pa_global_robustness_data.mat

    close all;
    outputFolder = fileparts(mfilename("fullpath"));
    baseParameters = pa_params();

    configuration = struct();
    configuration.sampleCount = 4096;
    configuration.randomSeed = 20260723;
    configuration.multiplierBounds = [0.8, 1.2];
    configuration.referenceZfixed = 0.05;
    configuration.referenceSodium = 0.0;
    configuration.comparisonSodium = 0.2;
    configuration.maximumAldosterone = 25.0;
    configuration.parameterNames = [ ...
        "alpha", "beta", "ka", "r0", "kr", "Kr", "pr", "Ks", ...
        "ns", "fmin", "Kf", "nf", "gz", "kz", "Kz", "nz"];

    fprintf("\nSimultaneous-parameter robustness analysis\n");
    fprintf("  Latin-hypercube samples: %d\n", configuration.sampleCount);
    fprintf("  simultaneous range: %.0f%% to %.0f%% of nominal\n", ...
        100*configuration.multiplierBounds(1), ...
        100*configuration.multiplierBounds(2));
    fprintf("  equilibrium parameters varied: %d\n", ...
        numel(configuration.parameterNames));

    unitDesign = latinHypercube( ...
        configuration.sampleCount, numel(configuration.parameterNames), ...
        configuration.randomSeed);
    lowerBound = configuration.multiplierBounds(1);
    upperBound = configuration.multiplierBounds(2);
    multipliers = lowerBound + (upperBound - lowerBound)*unitDesign;

    rootCount = zeros(configuration.sampleCount, 1, "uint8");
    stableRootCount = zeros(configuration.sampleCount, 1, "uint8");
    unexpectedStability = false(configuration.sampleCount, 1);
    oscillatoryInstability = false(configuration.sampleCount, 1);
    foldLowerSodium0 = nan(configuration.sampleCount, 1);
    foldUpperSodium0 = nan(configuration.sampleCount, 1);
    foldUpperSodium02 = nan(configuration.sampleCount, 1);
    hasPhysicalBistability = false(configuration.sampleCount, 1);
    unexpectedFoldGeometry = false(configuration.sampleCount, 1);

    progressInterval = 512;
    for sampleIndex = 1:configuration.sampleCount
        parameters = applyMultipliers( ...
            baseParameters, configuration.parameterNames, ...
            multipliers(sampleIndex, :));
        parameters.zfixed = configuration.referenceZfixed;
        parameters.sodium = configuration.referenceSodium;

        roots = findEquilibriumRoots( ...
            parameters, configuration.maximumAldosterone);
        rootCount(sampleIndex) = uint8(numel(roots));
        [stableRootCount(sampleIndex), ...
            oscillatoryInstability(sampleIndex)] = ...
            assessRootStability(roots, parameters);
        unexpectedStability(sampleIndex) = ...
            ~hasExpectedStabilityPattern( ...
            rootCount(sampleIndex), stableRootCount(sampleIndex));

        foldParameters = parameters;
        foldParameters.zfixed = 0.0;
        [foldLowerSodium0(sampleIndex), foldUpperSodium0(sampleIndex), ...
            unexpectedAtSodium0] = findPhysicalBistableInterval( ...
            foldParameters, configuration.maximumAldosterone);
        hasPhysicalBistability(sampleIndex) = ...
            isfinite(foldUpperSodium0(sampleIndex)) && ...
            foldUpperSodium0(sampleIndex) > ...
            max(0.0, foldLowerSodium0(sampleIndex));

        foldParameters.sodium = configuration.comparisonSodium;
        [~, foldUpperSodium02(sampleIndex), unexpectedAtSodium02] = ...
            findPhysicalBistableInterval( ...
            foldParameters, configuration.maximumAldosterone);
        unexpectedFoldGeometry(sampleIndex) = ...
            unexpectedAtSodium0 || unexpectedAtSodium02;

        if mod(sampleIndex, progressInterval) == 0
            fprintf("  processed %4d / %d samples\n", ...
                sampleIndex, configuration.sampleCount);
        end
    end

    sodiumFoldChange = foldUpperSodium02 - foldUpperSodium0;
    sodiumComparisonAvailable = ...
        isfinite(foldUpperSodium0) & isfinite(foldUpperSodium02);
    sodiumDirectionPreserved = ...
        sodiumComparisonAvailable & (sodiumFoldChange < 0.0);

    sampleTable = buildSampleTable( ...
        configuration, multipliers, rootCount, stableRootCount, ...
        hasPhysicalBistability, foldLowerSodium0, foldUpperSodium0, ...
        foldUpperSodium02, sodiumFoldChange, sodiumComparisonAvailable, ...
        sodiumDirectionPreserved, unexpectedStability, ...
        oscillatoryInstability, unexpectedFoldGeometry);

    associationTable = fitThresholdAssociations( ...
        multipliers, foldUpperSodium0, ...
        configuration.parameterNames);
    summaryTable = buildSummaryTable( ...
        configuration, rootCount, hasPhysicalBistability, ...
        foldUpperSodium0, foldUpperSodium02, sodiumFoldChange, ...
        sodiumComparisonAvailable, sodiumDirectionPreserved, ...
        unexpectedStability, oscillatoryInstability, ...
        unexpectedFoldGeometry);

    nominalParameters = baseParameters;
    nominalParameters.zfixed = 0.0;
    nominalParameters.sodium = configuration.referenceSodium;
    [~, nominalFoldSodium0] = findPhysicalBistableInterval( ...
        nominalParameters, configuration.maximumAldosterone);
    nominalParameters.sodium = configuration.comparisonSodium;
    [~, nominalFoldSodium02] = findPhysicalBistableInterval( ...
        nominalParameters, configuration.maximumAldosterone);

    figureHandle = createRobustnessFigure( ...
        rootCount, hasPhysicalBistability, foldUpperSodium0, ...
        foldUpperSodium02, sodiumFoldChange, ...
        sodiumComparisonAvailable, sodiumDirectionPreserved, ...
        associationTable, nominalFoldSodium0, nominalFoldSodium02);

    outputFiles = struct( ...
        png=fullfile(outputFolder, "pa_global_robustness.png"), ...
        pdf=fullfile(outputFolder, "pa_global_robustness.pdf"), ...
        summary=fullfile(outputFolder, "pa_global_robustness_summary.csv"), ...
        associations=fullfile( ...
            outputFolder, "pa_global_robustness_associations.csv"), ...
        samples=fullfile(outputFolder, "pa_global_robustness_samples.csv"), ...
        data=fullfile(outputFolder, "pa_global_robustness_data.mat"));

    exportgraphics(figureHandle, outputFiles.png, Resolution=300);
    exportgraphics(figureHandle, outputFiles.pdf, ContentType="vector");
    writetable(summaryTable, outputFiles.summary);
    writetable(associationTable, outputFiles.associations);
    writetable(sampleTable, outputFiles.samples);

    results = struct();
    results.configuration = configuration;
    results.summary = summaryTable;
    results.associations = associationTable;
    results.samples = sampleTable;
    results.nominalFoldSodium0 = nominalFoldSodium0;
    results.nominalFoldSodium02 = nominalFoldSodium02;
    results.outputFiles = outputFiles;
    save(outputFiles.data, "results");

    reportResults(results);
end

function design = latinHypercube(sampleCount, variableCount, randomSeed)
%LATINHYPERCUBE Generate a toolbox-independent randomized Latin hypercube.
    previousState = rng;
    cleanup = onCleanup(@() rng(previousState));
    rng(randomSeed, "twister");

    design = zeros(sampleCount, variableCount);
    for variableIndex = 1:variableCount
        strata = randperm(sampleCount)';
        design(:, variableIndex) = ...
            (strata - 1.0 + rand(sampleCount, 1))/sampleCount;
    end
    clear cleanup;
end

function parameters = applyMultipliers( ...
        baseParameters, parameterNames, multipliers)
    parameters = baseParameters;
    for parameterIndex = 1:numel(parameterNames)
        parameterName = parameterNames(parameterIndex);
        parameters.(parameterName) = ...
            baseParameters.(parameterName)*multipliers(parameterIndex);
    end
end

function [lowerFold, upperFold, unexpectedGeometry] = ...
        findPhysicalBistableInterval(parameters, maximumAldosterone)
%FINDPHYSICALBISTABLEINTERVAL Find folds from dR/da=0.
%
% z_fixed enters the scalar equilibrium residual additively as
% alpha*z_fixed. Therefore, stationary aldosterone values are independent
% of z_fixed. A local minimum followed by a local maximum defines a
% bistable interval. The local-minimum fold is the healthy-saddle threshold.

    grid = linspace(1.0e-7, maximumAldosterone, 3001);
    derivative = scalarEquilibriumDerivative(grid, parameters);
    crossingIndices = find( ...
        derivative(1:end - 1).*derivative(2:end) < 0.0);
    stationaryPoints = nan(numel(crossingIndices), 1);

    for index = 1:numel(crossingIndices)
        bracket = grid(crossingIndices(index):crossingIndices(index) + 1);
        stationaryPoints(index) = fzero( ...
            @(aldosterone) scalarEquilibriumDerivative( ...
            aldosterone, parameters), bracket);
    end
    stationaryPoints = unique(round(stationaryPoints, 11));

    lowerCandidates = [];
    upperCandidates = [];
    intervalWidths = [];
    pairCount = 0;
    for pointIndex = 1:(numel(stationaryPoints) - 1)
        firstPoint = stationaryPoints(pointIndex);
        secondPoint = stationaryPoints(pointIndex + 1);
        firstType = stationaryPointType(firstPoint, parameters);
        secondType = stationaryPointType(secondPoint, parameters);

        if (firstType == 1) && (secondType == -1)
            pairCount = pairCount + 1;
            upperCandidate = foldZfixed(firstPoint, parameters);
            lowerCandidate = foldZfixed(secondPoint, parameters);
            physicalWidth = upperCandidate - max(0.0, lowerCandidate);
            if physicalWidth > 0.0
                lowerCandidates(end + 1, 1) = lowerCandidate; %#ok<AGROW>
                upperCandidates(end + 1, 1) = upperCandidate; %#ok<AGROW>
                intervalWidths(end + 1, 1) = physicalWidth; %#ok<AGROW>
            end
        end
    end

    if isempty(intervalWidths)
        lowerFold = NaN;
        upperFold = NaN;
    else
        [~, bestIndex] = max(intervalWidths);
        lowerFold = lowerCandidates(bestIndex);
        upperFold = upperCandidates(bestIndex);
    end
    unexpectedGeometry = ...
        (numel(stationaryPoints) ~= 2) || (pairCount ~= 1);
end

function type = stationaryPointType(aldosterone, parameters)
% Return +1 for a local minimum, -1 for a local maximum, and 0 otherwise.
    step = 1.0e-5*max(1.0, aldosterone);
    leftDerivative = scalarEquilibriumDerivative( ...
        max(aldosterone - step, 0.0), parameters);
    rightDerivative = scalarEquilibriumDerivative( ...
        aldosterone + step, parameters);
    if (leftDerivative < 0.0) && (rightDerivative > 0.0)
        type = 1;
    elseif (leftDerivative > 0.0) && (rightDerivative < 0.0)
        type = -1;
    else
        type = 0;
    end
end

function zfixed = foldZfixed(aldosterone, parameters)
    zeroFloorParameters = parameters;
    zeroFloorParameters.zfixed = 0.0;
    residualAtZeroFloor = scalarEquilibriumResidual( ...
        aldosterone, zeroFloorParameters);
    zfixed = -residualAtZeroFloor/parameters.alpha;
end

function roots = findEquilibriumRoots(parameters, maximumAldosterone)
    grid = linspace(0.0, maximumAldosterone, 4001);
    residual = scalarEquilibriumResidual(grid, parameters);
    crossingIndices = find(residual(1:end - 1).*residual(2:end) < 0.0);
    roots = nan(numel(crossingIndices), 1);

    for index = 1:numel(crossingIndices)
        bracket = grid(crossingIndices(index):crossingIndices(index) + 1);
        roots(index) = fzero( ...
            @(aldosterone) scalarEquilibriumResidual( ...
            aldosterone, parameters), bracket);
    end
    roots = unique(round(roots, 11));
end

function [stableCount, hasOscillatoryInstability] = ...
        assessRootStability(roots, parameters)
    stableCount = uint8(0);
    hasOscillatoryInstability = false;
    for rootIndex = 1:numel(roots)
        state = stateFromAldosterone(roots(rootIndex), parameters);
        [residual, jacobian] = modelResidualAndJacobian(state, parameters);
        if norm(residual, inf) > 1.0e-7
            error("pa:robustness:EquilibriumResidual", ...
                "A sampled equilibrium failed full-model validation.");
        end
        eigenvalues = eig(jacobian);
        [maximumRealPart, leadingIndex] = max(real(eigenvalues));
        if maximumRealPart < -1.0e-7
            stableCount = stableCount + uint8(1);
        elseif (maximumRealPart > 1.0e-7) && ...
                (abs(imag(eigenvalues(leadingIndex))) > 1.0e-6)
            hasOscillatoryInstability = true;
        end
    end
end

function isExpected = hasExpectedStabilityPattern(rootCount, stableCount)
    isExpected = ...
        ((rootCount == 1) && (stableCount == 1)) || ...
        ((rootCount == 3) && (stableCount == 2));
end

function residual = scalarEquilibriumResidual(aldosterone, parameters)
    salt = saltTarget(aldosterone, parameters);
    renin = parameters.r0*(1.0 - salt)/parameters.kr;
    plasticCapacity = (parameters.gz/parameters.kz)* ...
        hillValue(salt, parameters.Kz, parameters.nz);
    activeFraction = parameters.fmin + ...
        (1.0 - parameters.fmin)* ...
        hillValue(salt, parameters.Kf, parameters.nf);
    reninProduction = parameters.beta* ...
        hillValue(renin, parameters.Kr, parameters.pr);

    residual = reninProduction + ...
        parameters.alpha*(parameters.zfixed + ...
        plasticCapacity.*activeFraction) - ...
        parameters.ka*aldosterone;
end

function derivative = scalarEquilibriumDerivative(aldosterone, parameters)
    rawSalt = hillValue( ...
        aldosterone, parameters.Ks, parameters.ns) + parameters.sodium;
    salt = min(max(rawSalt, 0.0), 0.999);
    unclamped = (rawSalt > 0.0) & (rawSalt < 0.999);
    saltDerivative = hillDerivative( ...
        aldosterone, parameters.Ks, parameters.ns).*unclamped;

    reninRatio = parameters.r0/parameters.kr;
    renin = reninRatio*(1.0 - salt);
    reninDerivative = -reninRatio*saltDerivative;

    sustain = hillValue(salt, parameters.Kz, parameters.nz);
    sustainDerivative = hillDerivative( ...
        salt, parameters.Kz, parameters.nz).*saltDerivative;
    activeFraction = parameters.fmin + ...
        (1.0 - parameters.fmin)* ...
        hillValue(salt, parameters.Kf, parameters.nf);
    activeDerivative = (1.0 - parameters.fmin)* ...
        hillDerivative(salt, parameters.Kf, parameters.nf).*saltDerivative;

    plasticScale = parameters.gz/parameters.kz;
    autonomousDerivative = plasticScale*( ...
        sustainDerivative.*activeFraction + ...
        sustain.*activeDerivative);
    reninProductionDerivative = parameters.beta* ...
        hillDerivative(renin, parameters.Kr, parameters.pr).* ...
        reninDerivative;

    derivative = reninProductionDerivative + ...
        parameters.alpha*autonomousDerivative - parameters.ka;
end

function state = stateFromAldosterone(aldosterone, parameters)
    salt = saltTarget(aldosterone, parameters);
    renin = parameters.r0*(1.0 - salt)/parameters.kr;
    plasticCapacity = (parameters.gz/parameters.kz)* ...
        hillValue(salt, parameters.Kz, parameters.nz);
    state = [renin; aldosterone; plasticCapacity; salt];
end

function [residual, jacobian] = ...
        modelResidualAndJacobian(state, parameters)
    renin = state(1);
    aldosterone = state(2);
    plasticCapacity = state(3);
    salt = state(4);

    activeFraction = parameters.fmin + ...
        (1.0 - parameters.fmin)* ...
        hillValue(salt, parameters.Kf, parameters.nf);
    sustainFraction = hillValue(salt, parameters.Kz, parameters.nz);
    reninFraction = hillValue(renin, parameters.Kr, parameters.pr);

    residual = [ ...
        parameters.r0*(1.0 - salt) - parameters.kr*renin; ...
        parameters.beta*reninFraction + ...
            parameters.alpha*(parameters.zfixed + ...
            plasticCapacity*activeFraction) - ...
            parameters.ka*aldosterone; ...
        parameters.eps*(-parameters.kz*plasticCapacity + ...
            parameters.gz*sustainFraction); ...
        (saltTarget(aldosterone, parameters) - salt)/parameters.tau_s];

    activeDerivative = (1.0 - parameters.fmin)* ...
        hillDerivative(salt, parameters.Kf, parameters.nf);
    sustainDerivative = hillDerivative( ...
        salt, parameters.Kz, parameters.nz);
    reninDerivative = hillDerivative( ...
        renin, parameters.Kr, parameters.pr);
    saltDerivative = saltTargetDerivative(aldosterone, parameters);

    jacobian = zeros(4, 4);
    jacobian(1, 1) = -parameters.kr;
    jacobian(1, 4) = -parameters.r0;
    jacobian(2, 1) = parameters.beta*reninDerivative;
    jacobian(2, 2) = -parameters.ka;
    jacobian(2, 3) = parameters.alpha*activeFraction;
    jacobian(2, 4) = ...
        parameters.alpha*plasticCapacity*activeDerivative;
    jacobian(3, 3) = -parameters.eps*parameters.kz;
    jacobian(3, 4) = ...
        parameters.eps*parameters.gz*sustainDerivative;
    jacobian(4, 2) = saltDerivative/parameters.tau_s;
    jacobian(4, 4) = -1.0/parameters.tau_s;
end

function salt = saltTarget(aldosterone, parameters)
    salt = min(max( ...
        hillValue(aldosterone, parameters.Ks, parameters.ns) + ...
        parameters.sodium, 0.0), 0.999);
end

function derivative = saltTargetDerivative(aldosterone, parameters)
    rawSalt = hillValue( ...
        aldosterone, parameters.Ks, parameters.ns) + parameters.sodium;
    if (rawSalt <= 0.0) || (rawSalt >= 0.999)
        derivative = 0.0;
    else
        derivative = hillDerivative( ...
            aldosterone, parameters.Ks, parameters.ns);
    end
end

function value = hillValue(input, halfSaturation, exponent)
    inputPower = input.^exponent;
    halfPower = halfSaturation^exponent;
    value = inputPower./(halfPower + inputPower);
end

function derivative = hillDerivative(input, halfSaturation, exponent)
    halfPower = halfSaturation^exponent;
    denominator = halfPower + input.^exponent;
    derivative = exponent*halfPower*input.^(exponent - 1)./ ...
        denominator.^2;
end

function sampleTable = buildSampleTable( ...
        configuration, multipliers, rootCount, stableRootCount, ...
        hasPhysicalBistability, lowerFold, upperFoldSodium0, ...
        upperFoldSodium02, sodiumFoldChange, sodiumComparisonAvailable, ...
        sodiumDirectionPreserved, unexpectedStability, ...
        oscillatoryInstability, unexpectedFoldGeometry)
    variableNames = configuration.parameterNames + "Multiplier";
    sampleTable = array2table(multipliers, VariableNames=variableNames);
    sampleTable = addvars(sampleTable, ...
        (1:configuration.sampleCount)', rootCount, stableRootCount, ...
        hasPhysicalBistability, lowerFold, upperFoldSodium0, ...
        upperFoldSodium02, sodiumFoldChange, sodiumComparisonAvailable, ...
        sodiumDirectionPreserved, unexpectedStability, ...
        oscillatoryInstability, unexpectedFoldGeometry, ...
        Before=1, NewVariableNames=[ ...
        "Sample", "EquilibriumCount", "StableEquilibriumCount", ...
        "HasPhysicalBistability", "LowerFoldSodium0", ...
        "UpperFoldSodium0", "UpperFoldSodium02", ...
        "SodiumFoldChange", "SodiumComparisonAvailable", ...
        "SodiumDirectionPreserved", "UnexpectedStability", ...
        "OscillatoryInstability", "UnexpectedFoldGeometry"]);
end

function associationTable = fitThresholdAssociations( ...
        multipliers, foldThreshold, parameterNames)
% Fit simultaneous main effects to the healthy-saddle fold location.
    valid = isfinite(foldThreshold);
    predictors = multipliers(valid, :);
    response = foldThreshold(valid);
    predictorMean = mean(predictors, 1);
    predictorScale = std(predictors, 0, 1);
    responseMean = mean(response);
    responseScale = std(response);
    standardizedPredictors = ...
        (predictors - predictorMean)./predictorScale;
    standardizedResponse = (response - responseMean)/responseScale;
    design = [ones(size(standardizedPredictors, 1), 1), ...
        standardizedPredictors];
    estimates = design \ standardizedResponse;
    coefficient = estimates(2:end);
    foldChangePerPredictorStandardDeviation = coefficient*responseScale;

    fittedResponse = design*estimates;
    residualSumSquares = sum((standardizedResponse - fittedResponse).^2);
    totalSumSquares = sum(standardizedResponse.^2);
    modelR2 = 1.0 - residualSumSquares/totalSumSquares;

    [~, order] = sort(abs(coefficient), "descend");
    rank = zeros(numel(parameterNames), 1);
    rank(order) = (1:numel(parameterNames))';
    associationTable = table( ...
        parameterNames', coefficient, ...
        foldChangePerPredictorStandardDeviation, ...
        repmat(modelR2, numel(parameterNames), 1), rank, ...
        VariableNames=[ ...
        "Parameter", "StandardizedFoldCoefficient", ...
        "FoldChangePerPredictorStandardDeviation", ...
        "MainEffectsModelR2", "AbsoluteEffectRank"]);
    associationTable = sortrows(associationTable, "AbsoluteEffectRank");
end

function summaryTable = buildSummaryTable( ...
        configuration, rootCount, hasPhysicalBistability, ...
        upperFoldSodium0, upperFoldSodium02, sodiumFoldChange, ...
        sodiumComparisonAvailable, sodiumDirectionPreserved, ...
        unexpectedStability, oscillatoryInstability, ...
        unexpectedFoldGeometry)
    sampleCount = configuration.sampleCount;
    oneEquilibrium = rootCount == 1;
    threeEquilibria = rootCount == 3;
    unexpectedRootCount = ~(oneEquilibrium | threeEquilibria);

    statistic = strings(0, 1);
    estimate = zeros(0, 1);
    lower = zeros(0, 1);
    upper = zeros(0, 1);
    unit = strings(0, 1);
    denominator = zeros(0, 1);
    intervalType = strings(0, 1);

    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "One equilibrium at reference point", nnz(oneEquilibrium), ...
        sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Three equilibria at reference point", nnz(threeEquilibria), ...
        sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Any physical bistable z_fixed interval", ...
        nnz(hasPhysicalBistability), sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Sodium comparison evaluable", ...
        nnz(sodiumComparisonAvailable), sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Sodium lowers upper fold among evaluable samples", ...
        nnz(sodiumDirectionPreserved), nnz(sodiumComparisonAvailable));
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Unexpected equilibrium count", nnz(unexpectedRootCount), ...
        sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Unexpected full-Jacobian stability pattern", ...
        nnz(unexpectedStability), sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Oscillatory instability detected", ...
        nnz(oscillatoryInstability), sampleCount);
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendProportion(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Unexpected fold geometry", ...
        nnz(unexpectedFoldGeometry), sampleCount);

    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendDistribution(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Upper fold at sodium 0", upperFoldSodium0, "z_fixed");
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendDistribution(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Upper fold at sodium 0.2", upperFoldSodium02, "z_fixed");
    [statistic, estimate, lower, upper, unit, denominator, intervalType] = ...
        appendDistribution(statistic, estimate, lower, upper, unit, ...
        denominator, intervalType, ...
        "Sodium-induced upper-fold change", ...
        sodiumFoldChange(sodiumComparisonAvailable), "z_fixed");

    summaryTable = table( ...
        statistic, estimate, lower, upper, unit, denominator, intervalType, ...
        VariableNames=[ ...
        "Statistic", "Estimate", "Lower", "Upper", "Unit", ...
        "Denominator", "IntervalType"]);
end

function [statistic, estimate, lower, upper, unit, denominator, ...
        intervalType] = appendProportion( ...
        statistic, estimate, lower, upper, unit, denominator, ...
        intervalType, label, successCount, trialCount)
    if trialCount == 0
        proportion = NaN;
        confidenceInterval = [NaN, NaN];
    else
        proportion = successCount/trialCount;
        confidenceInterval = wilsonInterval(successCount, trialCount);
    end
    statistic(end + 1, 1) = label;
    estimate(end + 1, 1) = 100.0*proportion;
    lower(end + 1, 1) = 100.0*confidenceInterval(1);
    upper(end + 1, 1) = 100.0*confidenceInterval(2);
    unit(end + 1, 1) = "percent";
    denominator(end + 1, 1) = trialCount;
    intervalType(end + 1, 1) = "Wilson 95% confidence interval";
end

function interval = wilsonInterval(successCount, trialCount)
    z = 1.95996398454005;
    proportion = successCount/trialCount;
    denominator = 1.0 + z^2/trialCount;
    center = (proportion + z^2/(2.0*trialCount))/denominator;
    halfWidth = z/denominator*sqrt( ...
        proportion*(1.0 - proportion)/trialCount + ...
        z^2/(4.0*trialCount^2));
    interval = [center - halfWidth, center + halfWidth];
end

function [statistic, estimate, lower, upper, unit, denominator, ...
        intervalType] = appendDistribution( ...
        statistic, estimate, lower, upper, unit, denominator, ...
        intervalType, label, values, valueUnit)
    finiteValues = values(isfinite(values));
    statistic(end + 1, 1) = label;
    denominator(end + 1, 1) = numel(finiteValues);
    unit(end + 1, 1) = valueUnit;
    intervalType(end + 1, 1) = "median and empirical 2.5th-97.5th percentiles";
    if isempty(finiteValues)
        estimate(end + 1, 1) = NaN;
        lower(end + 1, 1) = NaN;
        upper(end + 1, 1) = NaN;
    else
        quantiles = empiricalQuantile(finiteValues, [0.025, 0.5, 0.975]);
        estimate(end + 1, 1) = quantiles(2);
        lower(end + 1, 1) = quantiles(1);
        upper(end + 1, 1) = quantiles(3);
    end
end

function quantiles = empiricalQuantile(values, probabilities)
    sortedValues = sort(values(:));
    count = numel(sortedValues);
    positions = 1.0 + (count - 1.0)*probabilities;
    lowerIndices = floor(positions);
    upperIndices = ceil(positions);
    fractions = positions - lowerIndices;
    quantiles = sortedValues(lowerIndices).*(1.0 - fractions(:)) + ...
        sortedValues(upperIndices).*fractions(:);
    quantiles = quantiles';
end

function figureHandle = createRobustnessFigure( ...
        rootCount, hasPhysicalBistability, upperFoldSodium0, ...
        upperFoldSodium02, sodiumFoldChange, sodiumComparisonAvailable, ...
        sodiumDirectionPreserved, associationTable, ...
        nominalFoldSodium0, nominalFoldSodium02)
    sampleCount = numel(rootCount);
    onePercent = 100.0*nnz(rootCount == 1)/sampleCount;
    threePercent = 100.0*nnz(rootCount == 3)/sampleCount;
    physicalPercent = 100.0*nnz(hasPhysicalBistability)/sampleCount;
    preservedPercent = 100.0*nnz(sodiumDirectionPreserved)/ ...
        max(1, nnz(sodiumComparisonAvailable));

    colorBlue = [0.15, 0.43, 0.72];
    colorOrange = [0.90, 0.45, 0.12];
    colorGreen = [0.18, 0.60, 0.38];
    colorRed = [0.76, 0.22, 0.20];

    figureHandle = figure( ...
        Name="Simultaneous-parameter robustness of PA bistability", ...
        Color="white", Position=[80, 80, 1500, 1050]);
    layout = tiledlayout(figureHandle, 2, 2, ...
        TileSpacing="compact", Padding="compact");
    title(layout, ...
        sprintf(['Simultaneous-parameter robustness ' ...
        '(N = %d Latin-hypercube samples; 80%%-120%% of nominal)'], ...
        sampleCount), ...
        FontSize=17, FontWeight="bold");

    axesA = nexttile(layout, 1);
    barValues = [onePercent, threePercent, physicalPercent, preservedPercent];
    bars = bar(axesA, barValues, 0.68, FaceColor="flat");
    bars.CData = [colorOrange; colorBlue; colorGreen; colorGreen];
    ylabel(axesA, "Samples (%)");
    xticks(axesA, 1:4);
    xticklabels(axesA, { ...
        "1 equilibrium", "3 equilibria", ...
        "Any physical\newlinebistability", ...
        "Sodium direction\newlinepreserved"});
    ylim(axesA, [0, 108]);
    grid(axesA, "on");
    axesA.YGrid = "on";
    axesA.XGrid = "off";
    for index = 1:numel(barValues)
        text(axesA, index, barValues(index) + 2.0, ...
            sprintf("%.1f%%", barValues(index)), ...
            HorizontalAlignment="center", FontWeight="bold");
    end
    title(axesA, "A  Robustness outcomes", ...
        HorizontalAlignment="left", FontWeight="bold");

    axesB = nexttile(layout, 2);
    hold(axesB, "on");
    histogram(axesB, upperFoldSodium0(isfinite(upperFoldSodium0)), ...
        35, Normalization="probability", FaceColor=colorBlue, ...
        FaceAlpha=0.55, EdgeColor="none", ...
        DisplayName="\sigma = 0");
    histogram(axesB, upperFoldSodium02(isfinite(upperFoldSodium02)), ...
        35, Normalization="probability", FaceColor=colorOrange, ...
        FaceAlpha=0.55, EdgeColor="none", ...
        DisplayName="\sigma = 0.2");
    xline(axesB, nominalFoldSodium0, "-", ...
        Color=colorBlue, LineWidth=2.0, HandleVisibility="off");
    xline(axesB, nominalFoldSodium02, "-", ...
        Color=colorOrange, LineWidth=2.0, HandleVisibility="off");
    xlabel(axesB, "Healthy-saddle fold, z_{fixed}^*");
    ylabel(axesB, "Fraction per bin");
    grid(axesB, "on");
    legend(axesB, Location="northeast", Box="off");
    title(axesB, "B  Distribution of remission thresholds", ...
        HorizontalAlignment="left", FontWeight="bold");

    axesC = nexttile(layout, 3);
    topCount = min(10, height(associationTable));
    topAssociations = associationTable(1:topCount, :);
    coefficients = flipud( ...
        topAssociations.StandardizedFoldCoefficient);
    labels = flipud(topAssociations.Parameter);
    bars = barh(axesC, coefficients, FaceColor="flat");
    bars.CData = repmat(colorGreen, topCount, 1);
    bars.CData(coefficients < 0.0, :) = ...
        repmat(colorRed, nnz(coefficients < 0.0), 1);
    yticks(axesC, 1:topCount);
    yticklabels(axesC, labels);
    xline(axesC, 0.0, "k-");
    xlabel(axesC, ...
        "Standardized multiple-regression coefficient");
    grid(axesC, "on");
    axesC.YGrid = "off";
    annotationText = ...
        "Positive = higher remission-capable threshold";
    text(axesC, 0.02, 0.03, annotationText, ...
        Units="normalized", FontSize=10, ...
        VerticalAlignment="bottom");
    modelR2 = topAssociations.MainEffectsModelR2(1);
    text(axesC, 0.98, 0.03, sprintf("main-effects R^2 = %.3f", modelR2), ...
        Units="normalized", HorizontalAlignment="right", ...
        FontSize=10, VerticalAlignment="bottom");
    title(axesC, "C  Multivariable drivers of the fold threshold", ...
        HorizontalAlignment="left", FontWeight="bold");

    axesD = nexttile(layout, 4);
    validChanges = sodiumFoldChange(sodiumComparisonAvailable);
    histogram(axesD, validChanges, 35, ...
        FaceColor=colorGreen, FaceAlpha=0.75, EdgeColor="white");
    hold(axesD, "on");
    xline(axesD, 0.0, "k--", LineWidth=1.5);
    xlabel(axesD, ...
        "\Delta z_{fixed}^* = z_{fixed}^*(0.2) - z_{fixed}^*(0)");
    ylabel(axesD, "Samples");
    grid(axesD, "on");
    text(axesD, 0.03, 0.95, ...
        sprintf("%.1f%% below zero", preservedPercent), ...
        Units="normalized", VerticalAlignment="top", ...
        FontWeight="bold", FontSize=12);
    title(axesD, "D  Sodium-effect direction", ...
        HorizontalAlignment="left", FontWeight="bold");

    allAxes = findall(figureHandle, Type="axes");
    set(allAxes, FontName="Arial", FontSize=11, LineWidth=0.9, ...
        Box="off");
end

function reportResults(results)
    summaryTable = results.summary;
    lookup = @(label) summaryTable.Estimate( ...
        summaryTable.Statistic == label);

    fprintf("\nResults\n");
    fprintf("  one equilibrium at reference:   %.2f%%\n", ...
        lookup("One equilibrium at reference point"));
    fprintf("  three equilibria at reference: %.2f%%\n", ...
        lookup("Three equilibria at reference point"));
    fprintf("  any physical bistability:      %.2f%%\n", ...
        lookup("Any physical bistable z_fixed interval"));
    fprintf("  sodium direction preserved:    %.2f%% of evaluable samples\n", ...
        lookup("Sodium lowers upper fold among evaluable samples"));
    fprintf("  nominal folds: sigma=0 %.9f; sigma=0.2 %.9f\n", ...
        results.nominalFoldSodium0, results.nominalFoldSodium02);

    foldRow = summaryTable.Statistic == "Upper fold at sodium 0";
    fprintf("  sampled sigma=0 fold: median %.6f (2.5th-97.5th %.6f-%.6f)\n", ...
        summaryTable.Estimate(foldRow), summaryTable.Lower(foldRow), ...
        summaryTable.Upper(foldRow));
    changeRow = summaryTable.Statistic == ...
        "Sodium-induced upper-fold change";
    fprintf("  sodium fold change: median %.6f (2.5th-97.5th %.6f-%.6f)\n", ...
        summaryTable.Estimate(changeRow), ...
        summaryTable.Lower(changeRow), summaryTable.Upper(changeRow));

    fprintf("\nFiles\n");
    fprintf("  figure:       %s\n", results.outputFiles.png);
    fprintf("  summary table: %s\n", results.outputFiles.summary);
    fprintf("  associations: %s\n", results.outputFiles.associations);
    fprintf("  sample data:  %s\n", results.outputFiles.samples);
    fprintf("  MAT data:     %s\n", results.outputFiles.data);
end
